name: Docker Image CI

on:  
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Node
      uses: actions/setup-node@v3.6.0
      with:
        node-version: '18.x'
    - uses: actions/checkout@dev
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag websajtika:$(date +%s)
